/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeamDetailsRouteImport } from './routes/team-details'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as RegulatoryUpdatesIndexRouteImport } from './routes/regulatory-updates/index'
import { Route as RegulatoryUpdatesSlugRouteImport } from './routes/regulatory-updates/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesAttendanceAndLeaveRouteImport } from './routes/services/attendance-and-leave'
import { Route as ServicesHrLabourCompliancesRouteImport } from './routes/services/hr-labour-compliances'
import { Route as ServicesHrOperationsRouteImport } from './routes/services/hr-operations'
import { Route as ServicesPayrollProcessingRouteImport } from './routes/services/payroll-processing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamDetailsRoute = TeamDetailsRouteImport.update({
  id: '/team-details',
  path: '/team-details',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryUpdatesIndexRoute = RegulatoryUpdatesIndexRouteImport.update({
  id: '/regulatory-updates/',
  path: '/regulatory-updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryUpdatesSlugRoute = RegulatoryUpdatesSlugRouteImport.update({
  id: '/regulatory-updates/$slug',
  path: '/regulatory-updates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAttendanceAndLeaveRoute =
  ServicesAttendanceAndLeaveRouteImport.update({
    id: '/services/attendance-and-leave',
    path: '/services/attendance-and-leave',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHrLabourCompliancesRoute =
  ServicesHrLabourCompliancesRouteImport.update({
    id: '/services/hr-labour-compliances',
    path: '/services/hr-labour-compliances',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHrOperationsRoute = ServicesHrOperationsRouteImport.update({
  id: '/services/hr-operations',
  path: '/services/hr-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPayrollProcessingRoute =
  ServicesPayrollProcessingRouteImport.update({
    id: '/services/payroll-processing',
    path: '/services/payroll-processing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team': typeof TeamRoute
  '/team-details': typeof TeamDetailsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/regulatory-updates/$slug': typeof RegulatoryUpdatesSlugRoute
  '/services/attendance-and-leave': typeof ServicesAttendanceAndLeaveRoute
  '/services/hr-labour-compliances': typeof ServicesHrLabourCompliancesRoute
  '/services/hr-operations': typeof ServicesHrOperationsRoute
  '/services/payroll-processing': typeof ServicesPayrollProcessingRoute
  '/regulatory-updates/': typeof RegulatoryUpdatesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team': typeof TeamRoute
  '/team-details': typeof TeamDetailsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/regulatory-updates/$slug': typeof RegulatoryUpdatesSlugRoute
  '/services/attendance-and-leave': typeof ServicesAttendanceAndLeaveRoute
  '/services/hr-labour-compliances': typeof ServicesHrLabourCompliancesRoute
  '/services/hr-operations': typeof ServicesHrOperationsRoute
  '/services/payroll-processing': typeof ServicesPayrollProcessingRoute
  '/regulatory-updates': typeof RegulatoryUpdatesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team': typeof TeamRoute
  '/team-details': typeof TeamDetailsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/regulatory-updates/$slug': typeof RegulatoryUpdatesSlugRoute
  '/services/attendance-and-leave': typeof ServicesAttendanceAndLeaveRoute
  '/services/hr-labour-compliances': typeof ServicesHrLabourCompliancesRoute
  '/services/hr-operations': typeof ServicesHrOperationsRoute
  '/services/payroll-processing': typeof ServicesPayrollProcessingRoute
  '/regulatory-updates/': typeof RegulatoryUpdatesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy-policy'
    | '/team'
    | '/team-details'
    | '/terms-and-conditions'
    | '/vision-mission'
    | '/regulatory-updates/$slug'
    | '/services/attendance-and-leave'
    | '/services/hr-labour-compliances'
    | '/services/hr-operations'
    | '/services/payroll-processing'
    | '/regulatory-updates/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy-policy'
    | '/team'
    | '/team-details'
    | '/terms-and-conditions'
    | '/vision-mission'
    | '/regulatory-updates/$slug'
    | '/services/attendance-and-leave'
    | '/services/hr-labour-compliances'
    | '/services/hr-operations'
    | '/services/payroll-processing'
    | '/regulatory-updates'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy-policy'
    | '/team'
    | '/team-details'
    | '/terms-and-conditions'
    | '/vision-mission'
    | '/regulatory-updates/$slug'
    | '/services/attendance-and-leave'
    | '/services/hr-labour-compliances'
    | '/services/hr-operations'
    | '/services/payroll-processing'
    | '/regulatory-updates/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TeamRoute: typeof TeamRoute
  TeamDetailsRoute: typeof TeamDetailsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  VisionMissionRoute: typeof VisionMissionRoute
  RegulatoryUpdatesSlugRoute: typeof RegulatoryUpdatesSlugRoute
  ServicesAttendanceAndLeaveRoute: typeof ServicesAttendanceAndLeaveRoute
  ServicesHrLabourCompliancesRoute: typeof ServicesHrLabourCompliancesRoute
  ServicesHrOperationsRoute: typeof ServicesHrOperationsRoute
  ServicesPayrollProcessingRoute: typeof ServicesPayrollProcessingRoute
  RegulatoryUpdatesIndexRoute: typeof RegulatoryUpdatesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-details': {
      id: '/team-details'
      path: '/team-details'
      fullPath: '/team-details'
      preLoaderRoute: typeof TeamDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-updates/': {
      id: '/regulatory-updates/'
      path: '/regulatory-updates'
      fullPath: '/regulatory-updates/'
      preLoaderRoute: typeof RegulatoryUpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-updates/$slug': {
      id: '/regulatory-updates/$slug'
      path: '/regulatory-updates/$slug'
      fullPath: '/regulatory-updates/$slug'
      preLoaderRoute: typeof RegulatoryUpdatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/attendance-and-leave': {
      id: '/services/attendance-and-leave'
      path: '/services/attendance-and-leave'
      fullPath: '/services/attendance-and-leave'
      preLoaderRoute: typeof ServicesAttendanceAndLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hr-labour-compliances': {
      id: '/services/hr-labour-compliances'
      path: '/services/hr-labour-compliances'
      fullPath: '/services/hr-labour-compliances'
      preLoaderRoute: typeof ServicesHrLabourCompliancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hr-operations': {
      id: '/services/hr-operations'
      path: '/services/hr-operations'
      fullPath: '/services/hr-operations'
      preLoaderRoute: typeof ServicesHrOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/payroll-processing': {
      id: '/services/payroll-processing'
      path: '/services/payroll-processing'
      fullPath: '/services/payroll-processing'
      preLoaderRoute: typeof ServicesPayrollProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TeamRoute: TeamRoute,
  TeamDetailsRoute: TeamDetailsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  VisionMissionRoute: VisionMissionRoute,
  RegulatoryUpdatesSlugRoute: RegulatoryUpdatesSlugRoute,
  ServicesAttendanceAndLeaveRoute: ServicesAttendanceAndLeaveRoute,
  ServicesHrLabourCompliancesRoute: ServicesHrLabourCompliancesRoute,
  ServicesHrOperationsRoute: ServicesHrOperationsRoute,
  ServicesPayrollProcessingRoute: ServicesPayrollProcessingRoute,
  RegulatoryUpdatesIndexRoute: RegulatoryUpdatesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
